### ISSUE TITLE
This project needs performance testing

### ISSUE THREAD

**Issue by dmitankin** [sdonkov/dawg#5]
There should be an automated way of measuring the impact of each change.
For memory consumption we can utilize something like [jol](https://www.baeldung.com/jvm-measuring-object-sizes) or use the JDK tooling and write scripts for extracting what we need.
For speed it'd be best to rely on custom code which takes into account tiered compilation. Another approach would be to utilize some of [these](https://stackoverflow.com/questions/7146207/what-is-the-best-macro-benchmarking-tool-framework-to-measure-a-single-threade).

**Comment by sdonkov** [comment]
#19
